name: create-compute

on: 
  workflow_call:
    inputs:
      cluster_name:
        required: true
        type: string
      size:  
        required: true
        type: string
      min_instances: 
        required: true
        type: number
      max_instances: 
        required: true
        type: number
      resource_group:   
        required: true
        type: string
      workspace_name:  
        required: true
        type: string
      cluster_tier: 
        required: false
        type: string
    secrets:
      creds:
        required: true

jobs:
  create-compute:
    runs-on: ubuntu-latest
    steps:
      - name: Az CLI login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.creds }}

      - name: Ensure Azure ML CLI extension is correct
        run: |
          # Remove any conflicting extensions
          az extension remove -n azure-cli-ml || true
          az extension remove -n ml             || true

          # Install the official 'ml' extension from the marketplace
          az extension add -n ml

          # Confirm only the 'ml' extension is active
          az extension list --output table

      - name: create-compute-default-tier
        if: ${{ inputs.cluster_tier == '' }}
        run: |
          az ml compute create \
            --name           "${{ inputs.cluster_name }}" \
            --type           AmlCompute \
            --tier           dedicated \
            --size           "${{ inputs.size }}" \
            --min-instances  "${{ inputs.min_instances }}" \
            --max-instances  "${{ inputs.max_instances }}" \
            --resource-group "${{ inputs.resource_group }}" \
            --workspace-name "${{ inputs.workspace_name }}"

      - name: create-compute-using-tier
        if: ${{ inputs.cluster_tier != '' }}
        run: |
          az ml compute create \
            --name           "${{ inputs.cluster_name }}" \
            --type           AmlCompute \
            --tier           "${{ inputs.cluster_tier }}" \
            --size           "${{ inputs.size }}" \
            --min-instances  "${{ inputs.min_instances }}" \
            --max-instances  "${{ inputs.max_instances }}" \
            --resource-group "${{ inputs.resource_group }}" \
            --workspace-name "${{ inputs.workspace_name }}"
            
