name: create-compute         # ← added the missing “n” here

on:
  workflow_call:
    inputs:
      cluster_name:
        required: true
        type: string
      size:
        required: true
        type: string
      min_instances:
        required: true
        type: number
      max_instances:
        required: true
        type: number
      resource_group:
        required: true
        type: string
      workspace_name:
        required: true
        type: string
      cluster_tier:
        required: false
        type: string
    secrets:
      creds:
        required: true
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:
  create-compute:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.creds }}

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Azure ML Python SDK
        run: |
          python -m pip install --upgrade pip
          pip install azure-ai-ml azure-identity

      - name: Create compute via Python SDK
        env:
          AZURE_CLIENT_ID:       ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID:       ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_SECRET:   ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: |
          python - << 'EOF'
            import os
            from azure.identity import ClientSecretCredential
            from azure.ai.ml import MLClient
            from azure.ai.ml.entities import AmlCompute

            # Authenticate
            cred = ClientSecretCredential(
                tenant_id=os.environ["AZURE_TENANT_ID"],
                client_id=os.environ["AZURE_CLIENT_ID"],
                client_secret=os.environ["AZURE_CLIENT_SECRET"],
            )

            ml = MLClient(
                cred,
                subscription_id=os.environ["AZURE_SUBSCRIPTION_ID"],
                resource_group_name="${{ inputs.resource_group }}",
                workspace_name="${{ inputs.workspace_name }}"
            )

            tier = "${{ inputs.cluster_tier }}" or "dedicated"
            compute = AmlCompute(
                name="${{ inputs.cluster_name }}",
                size="${{ inputs.size }}",
                min_instances=${{ inputs.min_instances }},
                max_instances=${{ inputs.max_instances }},
                tier=tier
            )

            ml.begin_create_or_update(compute).result()
            print(f"Compute '{compute.name}' created (tier {tier})")
          EOF
